# Generated by Django 4.2.5 on 2023-09-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='realease_date',
            new_name='release_date',
        ),
    ]
